### ISSUE TITLE
Key verification crashes under latest PHP versions

### ISSUE THREAD

**Issue by Firehed** [Firehed/webauthn-php#89]
https://github.com/php/php-src/issues/16870

```
Fatal error: Uncaught ValueError: base and exponent overflow in /in/lnhXp:4
Stack trace:
#0 /in/lnhXp(4): gmp_pow(Object(GMP), 3)
#1 {main}
  thrown in /in/lnhXp on line 4

Process exited with code 255.
```

https://3v4l.org/lnhXp

For now, **avoid updating to 8.4.1/8.3.14/8.2.26**.

**Comment by Girgias** [comment]
As I just mentioned in the thread, it seems you could use the fact that the overloading of `**` was missed by the broken "fix".

So you could rewrite it as: ``$gmpObject ** 3``, and it "should" work.
